sorcery:
  google:
    callback_url: 'http://127.0.0.1:3000/api/oauth/callback?provider=google'
  github:
    client_id: <%= Rails.application.credentials[:github][:development][:client_id] %>
    client_secret: <%= Rails.application.credentials[:github][:development][:client_secret] %>
    callback_url: 'http://127.0.0.1:3000/api/oauth/callback?provider=github'
